(() => {
const KEY_SESSION='auditoria365-vault-key-v1',enc=new TextEncoder();
let memoryKey=null,keyImportPromise=null,activityTimer=null;
const IDLE_LOCK_MS=15*60*1000;
const b64ToBytes=v=>Uint8Array.from(atob(v),c=>c.charCodeAt(0));
const bytesToB64=v=>{let b=v instanceof Uint8Array?v:new Uint8Array(v),s='';for(let i=0;i<b.length;i+=32768)s+=String.fromCharCode(...b.subarray(i,i+32768));return btoa(s)};
const wipe=v=>{try{if(v instanceof ArrayBuffer)new Uint8Array(v).fill(0);else if(ArrayBuffer.isView(v))v.fill(0)}catch{}};
const equal=(a,b)=>{if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a[i]^b[i];return d===0};
async function importMaster(raw){let source=raw instanceof Uint8Array?raw:b64ToBytes(raw),bytes=new Uint8Array(source);try{memoryKey=await crypto.subtle.importKey('raw',bytes,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);return memoryKey}finally{wipe(bytes);if(!(raw instanceof Uint8Array))wipe(source)}}
(function recoverSessionKey(){let raw=sessionStorage.getItem(KEY_SESSION);if(raw){keyImportPromise=importMaster(raw).finally(()=>{raw=''})}})();
async function material(password){let p=enc.encode(password);try{return await crypto.subtle.importKey('raw',p,'PBKDF2',false,['deriveBits','deriveKey'])}finally{wipe(p)}}
async function deriveBits(password,salt,iterations){return new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:b64ToBytes(salt),iterations},await material(password),256))}
async function deriveKey(password,salt,iterations,usages=['decrypt']){return crypto.subtle.deriveKey({name:'PBKDF2',hash:'SHA-256',salt:b64ToBytes(salt),iterations},await material(password),{name:'AES-GCM',length:256},false,usages)}
async function buildCredentials(email,password){let rawB64=sessionStorage.getItem(KEY_SESSION);if(!rawB64)throw new Error('VAULT_LOCKED');let raw=b64ToBytes(rawB64),iterations=310000,authSalt=bytesToB64(crypto.getRandomValues(new Uint8Array(16))),vaultSalt=bytesToB64(crypto.getRandomValues(new Uint8Array(16))),iv=crypto.getRandomValues(new Uint8Array(12));try{let verifier=await deriveBits(password,authSalt,iterations),key=await deriveKey(password,vaultSalt,iterations,['encrypt']),wrapped=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:enc.encode(email)},key,raw);return {auth:{iterations,salt:authSalt,verifier:bytesToB64(verifier)},vault:{iterations,salt:vaultSalt,iv:bytesToB64(iv),wrappedKey:bytesToB64(wrapped)}}}finally{wipe(raw);wipe(iv)}}
async function authenticateUser(user,password){let v=await deriveBits(password,user.auth.salt,user.auth.iterations);let ok=equal(v,b64ToBytes(user.auth.verifier));wipe(v);if(!ok)return false;try{let k=await deriveKey(password,user.vault.salt,user.vault.iterations),raw=await crypto.subtle.decrypt({name:'AES-GCM',iv:b64ToBytes(user.vault.iv),additionalData:enc.encode(user.email)},k,b64ToBytes(user.vault.wrappedKey)),bytes=new Uint8Array(raw);if(bytes.length!==32){wipe(bytes);return false}sessionStorage.setItem(KEY_SESSION,bytesToB64(bytes));await importMaster(bytes);wipe(bytes);resetIdleLock();return true}catch{return false}}
function clearKey(){memoryKey=null;keyImportPromise=null;sessionStorage.removeItem(KEY_SESSION);if(activityTimer)clearTimeout(activityTimer)}
function hasKey(){return !!memoryKey||!!keyImportPromise||!!sessionStorage.getItem(KEY_SESSION)}
async function masterKey(){if(keyImportPromise){await keyImportPromise;keyImportPromise=null}if(!memoryKey)throw new Error('VAULT_LOCKED');return memoryKey}
function resetIdleLock(){if(activityTimer)clearTimeout(activityTimer);activityTimer=setTimeout(()=>{clearKey();window.dispatchEvent(new CustomEvent('a365-vault-locked'))},IDLE_LOCK_MS)}
['pointerdown','keydown','touchstart'].forEach(n=>addEventListener(n,resetIdleLock,{passive:true}));
async function sha256(buf){return bytesToB64(await crypto.subtle.digest('SHA-256',buf))}
async function encryptFile(file,storageId){let plain=new Uint8Array(await file.arrayBuffer()),iv=crypto.getRandomValues(new Uint8Array(12));try{let ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:enc.encode(storageId)},await masterKey(),plain);return {version:2,algorithm:'AES-256-GCM',iv:bytesToB64(iv),ciphertext,sha256:await sha256(plain),mimeType:file.type||'application/octet-stream',originalSize:file.size,createdAt:new Date().toISOString()}}finally{wipe(plain);wipe(iv)}}
async function decryptBytes(record,storageId){if(!record?.ciphertext||record.algorithm!=='AES-256-GCM')throw new Error('INVALID_RECORD');let plain=new Uint8Array(await crypto.subtle.decrypt({name:'AES-GCM',iv:b64ToBytes(record.iv),additionalData:enc.encode(storageId)},await masterKey(),record.ciphertext));if(await sha256(plain)!==record.sha256){wipe(plain);throw new Error('INTEGRITY_ERROR')}resetIdleLock();return plain}
async function decryptRecord(record,storageId){if(record instanceof Blob)return record;let plain=await decryptBytes(record,storageId);try{return new Blob([plain],{type:record.mimeType||'application/octet-stream'})}finally{wipe(plain)}}
async function encryptJson(value,label='auditoria365-backup'){let plain=enc.encode(JSON.stringify(value)),iv=crypto.getRandomValues(new Uint8Array(12));try{let ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:enc.encode(label)},await masterKey(),plain);return {format:'A365BACKUP',version:1,algorithm:'AES-256-GCM',label,iv:bytesToB64(iv),ciphertext:bytesToB64(ciphertext),createdAt:new Date().toISOString()}}finally{wipe(plain);wipe(iv)}}
async function decryptJson(pkg){if(!pkg||pkg.format!=='A365BACKUP')throw new Error('INVALID_BACKUP');let plain=new Uint8Array(await crypto.subtle.decrypt({name:'AES-GCM',iv:b64ToBytes(pkg.iv),additionalData:enc.encode(pkg.label||'auditoria365-backup')},await masterKey(),b64ToBytes(pkg.ciphertext)));try{return JSON.parse(new TextDecoder().decode(plain))}finally{wipe(plain)}}
function clearMemoryOnly(){memoryKey=null;keyImportPromise=null;if(activityTimer)clearTimeout(activityTimer)}

window.A365Crypto={authenticateUser,buildCredentials,clearKey,hasKey,encryptFile,decryptRecord,decryptBytes,encryptJson,decryptJson,wipe,resetIdleLock,KEY_SESSION,IDLE_LOCK_MS};
})();
