function json(data, status = 200) { return Response.json(data,{status,headers:{"Cache-Control":"no-store"}}); }
function getCookie(request,name){for(const part of (request.headers.get("cookie")||"").split(";")){const [k,...v]=part.trim().split("=");if(k===name)return v.join("=");}return null;}
function b64ToBytes(v){const s=atob(v),b=new Uint8Array(s.length);for(let i=0;i<s.length;i++)b[i]=s.charCodeAt(i);return b;}
function bytesToB64(b){let s="";for(const x of b)s+=String.fromCharCode(x);return btoa(s);}
async function sha256Base64(v){return bytesToB64(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v))));}
function parseHash(v){const p=String(v||"").split("$");return p.length===4&&p[0]==="pbkdf2-sha256"?{iterations:Number(p[1]),salt:p[2],hash:p[3]}:null;}
function equal(a,b){if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a[i]^b[i];return d===0;}
async function verify(password,stored){const p=parseHash(stored);if(!p)return false;const km=await crypto.subtle.importKey("raw",new TextEncoder().encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt:b64ToBytes(p.salt),iterations:p.iterations},km,256);return equal(new Uint8Array(bits),b64ToBytes(p.hash));}
async function createHash(password){const iterations=210000,salt=crypto.getRandomValues(new Uint8Array(16));const km=await crypto.subtle.importKey("raw",new TextEncoder().encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt,iterations},km,256);return `pbkdf2-sha256$${iterations}$${bytesToB64(salt)}$${bytesToB64(new Uint8Array(bits))}`;}
function valid(v){return v.length>=10&&/[A-Z]/.test(v)&&/[a-z]/.test(v)&&/[0-9]/.test(v);}
async function currentUser(context){const token=getCookie(context.request,"a365_session");if(!token){const email=String(context.request.headers.get("Cf-Access-Authenticated-User-Email")||"").trim().toLowerCase();if(!email)return null;return context.env.DB.prepare(`SELECT id,password_hash FROM users WHERE LOWER(cloud_email)=? AND status='active' LIMIT 1`).bind(email).first();}return context.env.DB.prepare(`SELECT users.id,users.password_hash FROM sessions INNER JOIN users ON users.id=sessions.user_id WHERE sessions.token_hash=? AND sessions.revoked_at IS NULL AND sessions.expires_at>? AND users.status='active' LIMIT 1`).bind(await sha256Base64(token),new Date().toISOString()).first();}
export async function onRequestPut(context){try{const user=await currentUser(context);if(!user)return json({ok:false,message:"Sesión no válida."},401);const body=await context.request.json();const currentPassword=String(body?.currentPassword||""),newPassword=String(body?.newPassword||"");if(!valid(newPassword))return json({ok:false,message:"La nueva contraseña no cumple los requisitos."},400);if(!await verify(currentPassword,user.password_hash))return json({ok:false,message:"La contraseña actual no es correcta."},400);await context.env.DB.prepare(`UPDATE users SET password_hash=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(await createHash(newPassword),user.id).run();await context.env.DB.prepare(`UPDATE sessions SET revoked_at=CURRENT_TIMESTAMP WHERE user_id=? AND id NOT IN (SELECT id FROM sessions WHERE token_hash=? LIMIT 1)`).bind(user.id,await sha256Base64(getCookie(context.request,"a365_session"))).run();return json({ok:true});}catch(error){return json({ok:false,message:error?.message||"Error al cambiar la contraseña."},500);}}
